services:
  db:
    image: postgres:15 
    container_name: db_fastapi
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mini_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_fastapi
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mini_backend
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgresql://postgres:123456@db:5432/mini_backend
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
    - backend_net

# Adding the new FastAPI service
  new_service:
    build:
      context: ./new_service
      dockerfile: Dockerfile
    container_name: new_service_fastapi
    restart: always
    ports:
    - "8001:8001"
    networks:
    - backend_net

# Nginx reverse proxy service
  nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - web
      - new_service
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  postgres_data: